// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0EMUSTBy0BQQuNwq3ulXfPmEfPNrVia4',
    appId: '1:128413073265:web:8f360b4cfb70c4f44e00d0',
    messagingSenderId: '128413073265',
    projectId: 'catalogo-peliculas-ac618',
    authDomain: 'catalogo-peliculas-ac618.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-ac618.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD55Me6k_6IoKrVXLIV1B0PSd89NZ54I50',
    appId: '1:128413073265:android:dcc9042413f941614e00d0',
    messagingSenderId: '128413073265',
    projectId: 'catalogo-peliculas-ac618',
    storageBucket: 'catalogo-peliculas-ac618.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA11tiuPjESpUeyy29YCftEUMzC5ZzWFzk',
    appId: '1:128413073265:ios:a5f455f48ac9f8e44e00d0',
    messagingSenderId: '128413073265',
    projectId: 'catalogo-peliculas-ac618',
    storageBucket: 'catalogo-peliculas-ac618.firebasestorage.app',
    iosBundleId: 'com.example.catalogoPeliculas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA11tiuPjESpUeyy29YCftEUMzC5ZzWFzk',
    appId: '1:128413073265:ios:a5f455f48ac9f8e44e00d0',
    messagingSenderId: '128413073265',
    projectId: 'catalogo-peliculas-ac618',
    storageBucket: 'catalogo-peliculas-ac618.firebasestorage.app',
    iosBundleId: 'com.example.catalogoPeliculas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0EMUSTBy0BQQuNwq3ulXfPmEfPNrVia4',
    appId: '1:128413073265:web:0771ec73e1a52e304e00d0',
    messagingSenderId: '128413073265',
    projectId: 'catalogo-peliculas-ac618',
    authDomain: 'catalogo-peliculas-ac618.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-ac618.firebasestorage.app',
  );
}
